version: "3"
services:
  frontend:
    build:
      context: ./
      dockerfile: frontend.Dockerfile
    ports:
      - "10006:10006"
  backend:
    build:
      context: ./
      dockerfile: backend.Dockerfile
    ports:
      - "10011:10011"
